// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCollectionData(arg1) {
  return window['go']['main']['App']['GetCollectionData'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}
