// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCollectionData(arg1:string):Promise<string>;

export function GetCollections():Promise<Array<main.Collection>>;
